      - name: 🔑 Authenticate
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: 🏗️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: ☁️ Infra
        env:
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
        run: make infra ENV={{ENV}}
